#!/bin/sh

FILE=/usr/share/python_games/badswap.wav # WAS: warning.wav

echo "$@" >> /tmp/sb-beep

if [ "$1" = "irssi" ] || [ "$1" = "xchat" ] ; then
	FILE=/usr/share/python_games/badswap.wav # WAS: email.wav
fi

exec aplay -q $FILE &
